### ISSUE TITLE
Build error --  When building on centos with cmake 3.15.3 

### ISSUE THREAD

**Issue by Nheyer** [vgteam/odgi#158]
I get a compile error of : 
```
/public/home/nheyer/odgi/src/odgi.hpp:446:36: error: too many initializers for 'handlegraph::step_handle_t'
/public/home/nheyer/odgi/src/odgi.hpp:447:35: error: array must be initialized with a brace-enclosed initializer
         step_handle_t last = {0, 0};
```
This error dosn't occur on my local computer on linux mint

**Comment by Nheyer** [comment]
This issue is being caused by the use of GCC 5.5.0_7 and any gcc lower then it, I know it will compile with gcc 9.3+ 
I think the issue might boil down to nested name spaces, with is not supported by  G++ 14 ( the current flag in the CMakkLists.txt file) and is only supported starting with GCC 7+
