### PR TITLE
Path guided linear 1D SGD sorting

### PR DESCRIPTION
**Pull request by subwaystation**
This branch will explore a path guided, linear, 1D SGD sorting algorithm.

As the current 1D SGD is not aware of path information and memory consumption scales quadratically, this new sort will try to address these issues.

Current plan: https://docs.google.com/presentation/d/1DDLPl4Jyxo4meNHzNDA5oPVMPceVtJxiYNOLJAsey30/edit?usp=sharing

### CODE REVIEW

**Comment by subwaystation** [comment]
Currently stuck at 
```
In file included from /home/heumos/git/odgi/src/algorithms/path_sgd.hpp:19,
                 from /home/heumos/git/odgi/src/algorithms/path_sgd.cpp:1:
/home/heumos/git/odgi/deps/cpp_random_distributions/zipfian_int_distribution.h:105:5: error: expected unqualified-id before ‘friend’
  105 |     friend bool operator==(const param_type& __p1, const param_type& __p2)
      |     ^~~~~~
make[2]: *** [CMakeFiles/odgi_objs.dir/build.make:1019: CMakeFiles/odgi_objs.dir/src/algorithms/path_sgd.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/heumos/git/odgi/src/algorithms/path_sgd.hpp:19,
                 from /home/heumos/git/odgi/src/subcommand/sort_main.cpp:15:
/home/heumos/git/odgi/deps/cpp_random_distributions/zipfian_int_distribution.h:105:5: error: expected unqualified-id before ‘friend’
  105 |     friend bool operator==(const param_type& __p1, const param_type& __p2)
      |     ^~~~~~
make[2]: *** [CMakeFiles/odgi_objs.dir/build.make:304: CMakeFiles/odgi_objs.dir/src/subcommand/sort_main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:222: CMakeFiles/odgi_objs.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

**Comment by subwaystation** [comment]
Now it builds but `git` says I did not do any changes....... this is weird......
Will have to resolve `Floating point exception (core dumped)` tomorrow. I bet it has something to do with the `abs` function.

**Comment by ekg** [comment]
I think it'd be good to generate a pathindex for the given graph internally if one isn't given. This would help make usage more ergonomic:

```
-> % odgi sort -i K-3138.32.odgi -o /dev/null -Y
[odgi sort] Error: Please specify a path index file to load the index via -X=[FILE], --path-index=[FILE]. A path index can be created with the 'odgi pathindex' command.
```

Given that this sorting algorithm is heavyweight, it'll probably only be a fraction of runtime to generate it. But it's still good to pass one in.

**Comment by ekg** [comment]
I'm working with this GFA file for testing: [K-3138.32.odgi.gfa.txt](https://github.com/vgteam/odgi/files/4721685/K-3138.32.odgi.gfa.txt)

```
odgi build -g K-3138.32.odgi.gfa -o K-3138.32.odgi
odgi pathindex -i K-3138.32.odgi -o K-3138.32.odgi.pidx
odgi sort -i K-3138.32.odgi -o /dev/null -Y -X K-3138.32.odgi.pidx
```

This yielded the following error:

```
odgi: /home/erik/odgi/build/sdsl-lite-prefix/src/sdsl-lite-build/include/sdsl/enc_vector.hpp:193: sdsl::enc_vector<t_coder, t_dens, t_width>::value_type sdsl::enc_vector<t_coder, t_dens, t_width>::operator[](sdsl::enc_vector<t_coder, t_dens, t_width>::size_type) const [with t_coder = sdsl::coder::elias_delta; unsigned int t_dens = 128; unsigned char t_width = 0; sdsl::enc_vector<t_coder, t_dens, t_width>::value_type = long unsigned int; sdsl::enc_vector<t_coder, t_dens, t_width>::size_type = long unsigned int]: Assertion `i < m_size' failed.
[1]    163839 abort (core dumped)  odgi sort -i K-3138.32.odgi -o /dev/null -Y -X K-3138.32.odgi.pidx
```

It looks like it's searching outside the length of the given path.

**Comment by ekg** [comment]
Maybe the zipf distribution domain should be the longest path length in the graph. This way it'll scale with graph size.

**Comment by subwaystation** [comment]
The current commit addresses all mentioned improvements above. Next step is the evaluation of the produced `pos_in_path_a` and `pos_in_path_b`.

**Comment by subwaystation** [comment]
@ekg Here are some steps to evaluate the current prototype.
`time odgi sort -i K-3138.32.odgi -o /dev/null -Y -X K-3138.32.odgi.pidx -t 1 2> K-3138.32.odgi.theta_0.99.tsv`

```R
k3 = read.table("K-3138.32.odgi.theta_0.99.tsv", header=F, sep="\t", as.is = TRUE, quote="")
colnames(k3) <- c("path_name", "pos_in_path_a", "pos_in_path_b", "term_distance")

png("K-3138.32.odgi.theta_0.99.hist.term_distance.png")
hist(k3$term_distance, breaks = 100)
dev.off()
png("K-3138.32.odgi.theta_0.99.hist.pos_in_path_a.png")
hist(k3$pos_in_path_a, breaks = 100)
dev.off()
png("K-3138.32.odgi.theta_0.99.hist.pos_in_path_b.png")
hist(k3$pos_in_path_b, breaks = 100)
dev.off()
png("K-3138.32.odgi.theta_0.99.barplot.path_name.png")
barplot(table(k3$path_name))
dev.off()
```
K-3138 32 odgi theta_0 99 hist term_distance
The `term_distances` look very Zipf like. This is what we want.
K-3138 32 odgi theta_0 99 barplot path_name
All paths are sampled equally likey, so I assume they have ~the same length?
K-3138 32 odgi theta_0 99 hist pos_in_path_a
`pos_in_path_a` looks good, except we see a drop at large path positions.
K-3138 32 odgi theta_0 99 hist pos_in_path_b
`pos_in_path_b` looks unexpected. We see a curve in the middle and we see a drop at large path positions.
